### ISSUE TITLE
Clean up issues and next milestone tasking

### ISSUE THREAD

**Issue by rennemannd** [ufosc/club-website#87]
Currently there is no clear direction for the website. Some of the issues are from before the react conversion. There are a few main goals we need to complete before the website is in normal working condition again:

- [ ] Convert the frontend to react hooks. This is required since it changes much of the structure.
- [ ] Revamp labels. The current labels need to be updated to better reflect the new direction of the project.
- [ ] Review all existing issues and either remove or rework them.
- [ ] Define a clear goal for v1.0 of the website. This includes intermediate milestones as well as any additional issues.

**Comment by rennemannd** [comment]
Wrapping this up (finally). Website has been totally converted to react hooks and is currently undergoing much needed updates for the authentication and user profile systems. They will now work with a separate backend in a different [ufosc repo ](https://github.com/ufosc/club-backend-ex). This means that documentation will also need to be overhauled for the website.
